---
apiVersion: v1
kind: Service
metadata:
  name: ray-head
spec:
  ports:
  - port: 6379
  selector:
    app: ray-head
---
apiVersion: v1
kind: Pod
metadata:
  name: ray-head
  labels:
    app: ray-head
spec:
  containers:
  - name: ray-head
    image: us.gcr.io/prophet-158422/ray
    ports:
    - containerPort: 6379
    command: [ "/bin/bash", "-c", "--" ]
    args: ["/ray/scripts/start_ray.sh --head --redis-port 6379 && while true; do sleep 30; done;"]
