---
apiVersion: v1
kind: Service
metadata:
  name: ray-head
spec:
  type: "LoadBalancer"
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: plasma
    port: 12345
    targetPort: 12345
  selector:
    app: ray-head
---
apiVersion: v1
kind: Pod
metadata:
  name: ray-head
  labels:
    app: ray-head
spec:
  containers:
  - name: ray-head
    image: us.gcr.io/prophet-158422/ray
    env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP 
    ports:
    - containerPort: 6379
    - containerPort: 12345
    command: [ "/bin/bash", "-c", "--" ]
    args: ["/ray/scripts/start_ray.sh --head --redis-port 6379 --object-manager-port 12345 --node-ip-address $MY_POD_IP && while true; do sleep 30; done;"]
